import { test, expect } from '@playwright/test';
test.use({ viewport: { width: 960, height: 640 } });
test.setTimeout(180_000);

test('Blacksite starts, shoots, reloads, changes stance, jumps, scopes, throws grenades and pauses', async ({ page }, testInfo) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.addInitScript(() => localStorage.setItem('nachtgang-blacksite-settings-v1', JSON.stringify({ difficulty: 'easy', quality: 'balanced', volume: 0 })));
  await page.goto('/');
  await expect(page.locator('#start-button')).toBeEnabled();
  await expect(page.locator('#loading')).toHaveClass(/done/);
  await page.screenshot({ path: testInfo.outputPath('blacksite-menu.png') });
  await page.getByRole('button', { name: '02 STEUERUNG ↗' }).click();
  await expect(page.locator('#help-dialog')).toBeVisible();
  await page.getByRole('button', { name: 'VERSTANDEN ↗' }).click();
  await page.getByRole('button', { name: '01 DEIN ARSENAL ↗' }).click();
  await expect(page.locator('#loadout-dialog')).toContainText('2,8 Sekunden');
  await page.getByRole('button', { name: 'BEREIT ↗' }).click();
  await page.locator('#start-button').click();
  await expect(page.locator('#hud')).toBeVisible();
  await expect(page.locator('#weapon-name')).toHaveText('AR-4 VANGUARD');
  await page.keyboard.down('KeyQ');
  await expect.poll(async () => Number(await page.locator('#ammo').textContent())).toBeLessThan(28);
  await page.keyboard.up('KeyQ');
  await page.keyboard.press('KeyR');
  await expect(page.locator('#reload-progress')).toBeVisible();
  await expect(page.locator('#ammo')).toHaveText('30');
  await page.keyboard.press('KeyC');
  await expect(page.locator('#stance')).toHaveText('LIEGEND');
  await page.keyboard.press('Space');
  await expect(page.locator('#stance')).toHaveText('STEHEND');
  await page.keyboard.press('Space');
  await expect(page.locator('#stance')).toHaveText('IN DER LUFT');
  await expect(page.locator('#stance')).toHaveText('STEHEND');
  await page.keyboard.press('Digit2');
  await expect(page.locator('#weapon-name')).toHaveText('M82 SENTINEL');
  await page.keyboard.down('KeyZ');
  await expect(page.locator('#scope')).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('blacksite-scope.png') });
  await page.keyboard.down('KeyQ');
  await expect(page.locator('#ammo')).toHaveText('04');
  await page.keyboard.up('KeyQ');
  await page.keyboard.up('KeyZ');
  await expect(page.locator('#scope')).not.toBeVisible();
  await page.keyboard.press('KeyG');
  await expect(page.locator('#grenades')).toHaveText('3');
  await page.keyboard.press('Escape');
  await expect(page.locator('#pause-screen')).toBeVisible();
  const objective = await page.locator('#objective-detail').textContent();
  await page.waitForTimeout(350);
  await expect(page.locator('#objective-detail')).toHaveText(objective);
  await page.locator('#resume-button').click();
  await expect(page.locator('#pause-screen')).not.toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('blacksite-gameplay.png') });
  await page.keyboard.press('Escape');
  await page.locator('#leave-button').click();
  await expect(page.locator('#menu')).toBeVisible();
  await page.locator('#start-button').click();
  await expect(page.locator('#health-value')).toHaveText('100');
  await expect(page.locator('#grenades')).toHaveText('4');
  await expect(page.locator('#ammo')).toHaveText('30');
  await page.keyboard.press('Escape');
  expect(errors).toEqual([]);
});

test('graphics preferences persist and desktop plus compact menus remain usable', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('#start-button')).toBeEnabled();
  await page.locator('#settings-button').click();
  await page.locator('#quality').selectOption('high');
  await page.locator('#difficulty').selectOption('hard');
  await page.getByRole('button', { name: 'FERTIG ↗' }).click();
  await expect(page.locator('#difficulty-label')).toHaveText('Veteran');
  await page.reload();
  await expect(page.locator('#start-button')).toBeEnabled();
  await expect(page.locator('#quality')).toHaveValue('high');
  await expect(page.locator('#difficulty')).toHaveValue('hard');
  await page.setViewportSize({ width: 640, height: 760 });
  await expect(page.locator('#start-button')).toBeInViewport();
  await page.locator('#help-button').click();
  await expect(page.locator('#help-dialog')).toBeVisible();
  await page.getByRole('button', { name: 'VERSTANDEN ↗' }).click();
  await expect(page.locator('#help-dialog')).not.toBeVisible();
});
